//
//  ProgressBarDraw.swift
//  ProjectName
//
//  Created by Joseph Hall on 5/22/17.
//  Copyright © 2017 Om Design. All rights reserved.
//
//  Generated by PaintCode
//  http://www.paintcodeapp.com
//



import UIKit

public class ProgressBarDraw : NSObject {
    
    //// Drawing Methods
    
    public dynamic class func drawTimer(frame: CGRect = CGRect(x: 43, y: 285, width: 357, height: 417), progress: CGFloat = 660) {
        //// General Declarations
        // This non-generic function dramatically improves compilation times of complex expressions.
        func fastFloor(_ x: CGFloat) -> CGFloat { return floor(x) }
        
        //// Color Declarations
        let color = UIColor(red: 0.108, green: 0.063, blue: 0.000, alpha: 0.827)
        
        //// Progress Border Drawing
        let progressBorderPath = UIBezierPath(ovalIn: CGRect(x: frame.minX + 14, y: frame.minY + 75, width: 300, height: 300))
        color.setFill()
        progressBorderPath.fill()
        UIColor.black.setStroke()
        progressBorderPath.lineWidth = 10
        progressBorderPath.stroke()
        
        
        //// Progress Active Drawing
        let progressActiveRect = CGRect(x: frame.minX + 19, y: frame.minY + 80, width: fastFloor((frame.width - 19) * 0.85799 + 0.5), height: fastFloor((frame.height - 80) * 0.86053 + 0.5))
        let progressActivePath = UIBezierPath()
        progressActivePath.addArc(withCenter: CGPoint(x: progressActiveRect.midX, y: progressActiveRect.midY), radius: progressActiveRect.width / 2, startAngle: -90 * CGFloat.pi/180, endAngle: -progress * CGFloat.pi/180, clockwise: true)
        progressActivePath.addLine(to: CGPoint(x: progressActiveRect.midX, y: progressActiveRect.midY))
        progressActivePath.close()
        
        UIColor.white.setFill()
        progressActivePath.fill()
    }
    
}
